categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
prev: Prev
next: Next
comment: Comments
contents: Contents
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
menu: Menu
weibo: Weibo
links: Links
rss: RSS
showsidebar: Show Sidebar
hidesidebar: Hide Sidebar
updated: Updated
totop: Back to Top
datepublished: Published
